//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KejaAsapAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Building()
        {
            this.BuildingPictures = new HashSet<BuildingPicture>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> AmenitiesId { get; set; }
        public string Location { get; set; }
        public string Floor { get; set; }
        public string Description { get; set; }
        public Nullable<long> OwnerId { get; set; }
    
        public virtual Amenity Amenity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildingPicture> BuildingPictures { get; set; }
        public virtual HouseOwner HouseOwner { get; set; }
    }
}
