//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KejaAsapAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingPicture
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long BuildingId { get; set; }
        public Nullable<bool> Path { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
